dataset_path: /mnt/3d/map3d/data/tum/extract
dataset_name: rgbd_dataset_freiburg3_walking_halfsphere
associations: /mnt/3d/map3d/data/associations/
width: 640
height: 480
fx: 535.4
fy: 539.2
cx: 320.1
cy: 247.6
depth_scale: 5000.0
yolo_model: yolov8x-seg.pt
conf_threshold: 0.5
seg_threshold: 80
ratio_threshold: 0.1
kernel_size: 5
eps: 0.05 # meter
min_points: 20
vote_threshold: 0.02 # meter
deform_threshold: 0.00015 
# use_visualization : 0